### ISSUE TITLE
[Feature] Setup project connection

### ISSUE THREAD

**Issue by roya0045** [MerginMaps/qgis-plugin#182]
I'm not sure about the wording and maybe this can be done somehow.

Basically I have my account on a remove machine and locally.

The main issue is that I can only update the projects from the source that has uploaded the project. I cannot 'connect' my other instance to the project. I can only download and do some other option.

Could I simply 'link' a project to a folder. This way all my sessions could be able to synchronize the projects by simply setting up the connection to their shared sources.

Let me know if this is unclear. Thanks!

**Comment by wonder-sk** [comment]
Hi Alex

it is not really clear to me what you are after - would you like to have one Mergin project downloaded multiple times to different directories on your computer?

Or maybe if you could provide more details for what you are trying to achieve, that would help...

**Comment by roya0045** [comment]
@wonder-sk Greetings Martin, sorry for the confusing post, here is the rundown:

Me and my colleagues use the same account to manage projects, the project is stored on a shared location. When we login the Mergin plugin, only the person that created the project has the ability to update it. Otherwise you can only download the project.

Since the source project is on a shared location everyone already has access to it, so no need to download. Having the ability to simply indicate where is the source project without downloading it would allow everyone to synchronize the local source.

Let me know if this makes more sense.

**Comment by wonder-sk** [comment]
@roya0045 Oh so you have the project in a folder shared with other people?

The idea is that every user has their own directory for the project they use. Different people then use different logins and the owner of the Mergin project can share it with other Mergin users - and each user can have a local directory on their local PC.

Using Mergin projects on a shared network volume is not recommended - especially because geopackages can get broken if more users modify them at once. This is one of the things that Mergin is supposed to resolve - everyone can have their own local copy, and Mergin takes care of merging changes from multiple people.

Does that make sense?

**Comment by roya0045** [comment]
Yes, but I was hoping for a way to let everyone have the capacity to sync a project. Admittedly our use case might be fringe. The goal of having a shared source is that everyone can update it in the field, everyone can see the related maps and update the data source with field collected data by syncing the project.

I agree that separated project are definitely safer, but having an advanced option to simply sync a project that was not setup by a used is nice.  We very rarely work on the source from the desktop so this risk is minimal to us and allowing anyone to refresh the 'local' source is more useful.

If it goes to harshly against the design I can close this, but having this option for users that understand the risks associated would be nice.

**Comment by wonder-sk** [comment]
> Yes, but I was hoping for a way to let everyone have the capacity to sync a project.

Maybe I am missing something - but in the scenario when each user has own project directory, everyone has the capacity to sync the project - or maybe you were referring to something else there?

It would be great if you could describe your use case of how the data flows between different people (in office and in field) - that would hopefully help me to fully understand your setup...

**Comment by roya0045** [comment]
Sure thing!

The main 'source' in on a shared server. To creathe the project the 'source' is uploaded to mergin'.
 Some maps are linked to the source itself.

 Anyone in the team can check the derived maps from the source as they display the field data. A few people can do field surveys.

 Once the surveys are done only one person can update the local source as the others don't have the 'connection' they can view the mergin folder and project, but only the original uploader can update the local source.

 Having to download and replace the original source to setup the 'connection' seems more risky than simply providing the location of the project source. 

What would be nice is to have each user be able to update the common source data in order to refresh the associated maps. There are no serate dataset per user, only the central one in the server.

We could have a unique source per user but this does not solve the issue as we would have to replace the data associated to the map with the most recent database that was synced.

**Comment by roya0045** [comment]
@wonder-sk  Just had another instance where simply connecting would be good. It seems that somehow the plugin lost the connections/track of folders. Despite the fact that all the folders are still there, I would have to redownload everything and validate conflicts manually or blindly overwrite the folders to recreate the connections.

**Comment by tomasMizera** [comment]
Hi @roya0045, this issue has been around for some time now. I am going to close the PR as it is stale now. Please approach me here or at `tomas.mizera@lutraconsulting.co.uk`, we can also schedule a call to better understand what you are trying to achieve.

**Comment by roya0045** [comment]
> Hi @roya0045, this issue has been around for some time now. I am going to close the PR as it is stale now. Please approach me here or at `tomas.mizera@lutraconsulting.co.uk`, we can also schedule a call to better understand what you are trying to achieve. 

As an alternative fix to my PR I just opted to create a script that generate or fix the needed QSettings for my colleagues.

**Comment by tomasMizera** [comment]
> > Hi @roya0045, this issue has been around for some time now. I am going to close the PR as it is stale now. Please approach me here or at `tomas.mizera@lutraconsulting.co.uk`, we can also schedule a call to better understand what you are trying to achieve.
> 
> As an alternative fix to my PR I just opted to create a script that generate or fix the needed QSettings for my colleagues.

Thanks for the update, in that case I am closing this ticket
