### ISSUE TITLE
Couldn't load plugin 'Mergin' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by waiotahi** [MerginMaps/qgis-plugin#538]
It was working fine yesterday but now I'm getting this error

Couldn't load plugin 'Mergin' due to an error when calling its classFactory() method 

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.30.1-'s-Hertogenbosch 's-Hertogenbosch, 9035a01e

**Comment by waiotahi** [comment]
I also tried to reinstall and I get this error
Plugin installation failed: Failed to unzip the plugin package. Probably it's broken or missing from the repository

**Comment by erpas** [comment]
Thanks @waiotahi for reporting the problem.

It is a known issue on Windows machines, please see https://github.com/MerginMaps/qgis-mergin-plugin/issues/504

A workaround to this is to try to uninstall the plugin (and get the permissions error), restart QGIS and install the plugin again.

**Comment by volcan01010** [comment]
Hi, this is a note to confirm that we have seen the same issue, that we only see it on Windows and that the workaround from @erpas allowed us to reinstall.

**Comment by waiotahi** [comment]
Thank you  @erpass - the workaround solved the problem

**Comment by alexbruy** [comment]
Duplicates #504.
