### ISSUE TITLE
Plugin flags the packaged mbtiles incorrectly as not available offline

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/qgis-plugin#540]
When I try to sync, I have a bunch of mbtiles files for offline use, but the plugin flags them along the online layers and warns me that they would not be available offline:
![image](https://github.com/MerginMaps/qgis-mergin-plugin/assets/2649047/49f46e66-6ce4-4789-bdf0-e641c071d9f1)

**Comment by jozef-budac** [comment]
Verified on 2024.1 RC
