### ISSUE TITLE
Better notification for already runing synchronization

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/qgis-plugin#561]
When on the mobile app I have a longer synchronization (for example with a bigger file) and then during it, I synchronize with a plugin, it shows this error. The error is correct but nicer notification would be better. For example, don't show 400 bad requests. 

![Screenshot at 2024-01-23 09-07-16](https://github.com/MerginMaps/qgis-plugin/assets/83582181/63009915-b841-4b38-95c0-f0ffd630e1be)

**Comment by jozef-budac** [comment]
SImilar for full storage
![Screenshot at 2024-01-23 09-18-39](https://github.com/MerginMaps/qgis-plugin/assets/83582181/5b687f77-4cba-4655-9d01-58f65093a636)

**Comment by Poulpator** [comment]
Added as part of the PR #601 that improve multiple dialog error

**Comment by alexd0793** [comment]
Testing done, looks nice as it should :)
