### ISSUE TITLE
Error in 'Extract local changes' tool

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/qgis-plugin#563]
When I have local changes in the project and try to extract them using the 'Extract local changes' tool, I get an error `TypeError: get_local_changes() missing 1 required positional argument: 'mp'`

Scenario:
D1: clone project [https://app.merginmaps.com/projects/input-testing/plugin_reporting_tool_advanced/tree](https://app.qase.io/run/PLUGIN/dashboard/27/plugin_reporting_tool_advanced)
in the project, find the polygon layer, there are 4 features. Delete one, update one, and create one. Save and DON'T synchronize.
D2: In QGIS go to Processing -> Toolbox -> Mergin Maps -> Tools -> Extract local changes
D3: A new window should appear
D4: in the "Project directory" find a path to the project, select "Input layer" to Polygon, and hit run
D5: A new "Local changes layer" should appear between layers, where changes should be visualized on the map and also in the attribute table of the new layer -> but I get an error
![Screenshot at 2024-01-23 10-37-13](https://github.com/MerginMaps/qgis-plugin/assets/83582181/faa81a55-eba6-4837-88c8-2c6f7445adcb)

**Comment by PatrikMizera** [comment]
TEST SUCCESFUL - A new "local changes layer" is created
