### ISSUE TITLE
The editor creates project conflict file

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/qgis-plugin#594]
According to the description "if both server and local changes are present on the files mergin is creating conflicted copy. Editors are not allowed to create conflicted copies of .qgs/qgz files in the file system by pull operation. "

However, I was able to create and upload the conflict file to the web app. 

Scenario:
1) have a simple project and open it with an admin user in QGIS
2) make a copy of the project for later use
3) Change project settings and "Project -> Properties -> General -> Units for distance measurement set to `Inches`
4) Synchronize the project with the server
5) log in to the plugin as an editor
6) replace the current project files with the files saved in step 2.
7) Change project settings and "Project -> Properties -> General -> Units for distance measurement set to `Yards`
8) Synchronize the project  
-> The plugin creates the conflict file which can be uploaded to mergin

**Comment by tomasMizera** [comment]
Hmm, weird, I tested this on Friday and it worked fine. Maybe something changed yesterday.

**Comment by tomasMizera** [comment]
Hi @jozef-budac I can not reproduce this issue. Can we have a call and test it together? :)

**Comment by jozef-budac** [comment]
Can't simulate is anymore. O maybe I did something wrong
