### ISSUE TITLE
Delete multiple photos from a project on the MerginMaps cloud

### ISSUE THREAD

**Issue by lefcgis** [MerginMaps/qgis-plugin#603]
Hi guys!

Is there an option to delete multiple photos (at the same time) on the MerginMaps cloud?. I have 2k photos, so it's embarrased to invest time deleting photo by photo, one by one. 

![multiple](https://github.com/user-attachments/assets/8a12b5b5-3b9c-44ec-8922-cec9090ff90c)

 
I really appreciate it!  :3

Lucho.
QGIS Perú

**Comment by tomasMizera** [comment]
Hi @lefcgis, there is no bulk edit in the web dashboard at the moment. What you can do instead is to remove the photos from the folder on your disk and then hit synchronize in the QGIS plugin. I saw your comment on our community Slack channel, let's proceed with the discussion there! :)
