### ISSUE TITLE
External photo storage

### ISSUE THREAD

**Issue by Ellebjerg** [MerginMaps/qgis-plugin#606]
One of our projects has exceeded 4 GB of storage within the first couple of months of operation due to photos. We are therefore looking at storage outside the project. We would prefer to store the photos on our own server outside the municipal firewall instead of using Amazon S3 or similar, but as we read your online guides this is not supported.
Do you have plans for supporting this way off storing photos?

**Comment by tomasMizera** [comment]
Hello @Ellebjerg, thanks for your suggestion! You can use [Media Sync](https://github.com/MerginMaps/media-sync) to move your photos to your self-hosted MinIO object store. Check out the [quick start guide](https://github.com/MerginMaps/media-sync/blob/main/docs/quick_start.md) for instructions. If you'd be interested in other type of storage, let us know on info@merginmaps.com or file a request on our wishlist portal: https://wishlist.merginmaps.com
