### ISSUE TITLE
Unable to compare some of the modified files with their server version - their history will be lost if uploaded.

### ISSUE THREAD

**Issue by lefcgis** [MerginMaps/qgis-plugin#608]
Hi!

I added two new variables to calculate latitude and longitude (with $y and $x expressions). Then, I saved layer changes. Then, I saved the qgz project and finally, I tried to synchronize changes without success. However, Project status prompt told me that: "Unable to compare some of the modified files with their server version - their history will be lost if uploaded."

![Captura](https://github.com/user-attachments/assets/e351b6b1-3d91-44fc-99cd-27c5b34c0847)

Please, let me know if I have skipped some steps.

Regards,

Lucho 🇵🇪

**Comment by ValentinBuira** [comment]
Hi Lucho, thanks for the bug report

Please note, making changes in the data schema of layers can lead to issues in the synchronization process. This behavior is expected ( see https://merginmaps.com/docs/manage/deploy-new-project/ for more details). 

I forwarded your demand to the support, you can also join the [slack community server ](https://merginmaps.com/community/join)for help
