### ISSUE TITLE
When i tried to open the project on the movil app it apears that error

### ISSUE THREAD

**Issue by camicasilo** [MerginMaps/qgis-plugin#619]
231PMOME O -- 0O am: 24O
< Errores del Proyecto
Capa: AI_FB_Preliminar_20240912
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/AI_FB_Prelimínar_2024091Z.gpkgl
layername=AlI_FB_Preliminar_20240912
Capa: Administrativo_P
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Administrativo_P.gpkg|
layername=Administrativo_P
Capa: Bloques_EsteroAB_20240912
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Bloques_EsteroAB_20240912.gpkg|
layername=Bloques_EsteroAB_20240912
Capa: Colombia
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Colombia.gpkg|layername=Colombia
Capa: Construccion_P_20240912
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Construccion_P_20240912.gpkg|
layername=Construccion_P_20240912
o o - T
Escaneado con CamScanner
9:31PM © I & O -
< Errores del Proyecto
Capa: Construccion_P
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Construccion_P.gpkg|
layername=Construccion_P
Capa: Croquis
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Croquis.gpkgIIayername:Croquis
Capa: Curva_Nivel
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Curva_Nivel.gpkg|
layername=Curva_Nivel
Capa: Departamentos
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Departamentos.gpkg|
layername=Departamentos
Capa: Drenaje_Doble
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Drenaje_Doble.gpkg|
o o - T
Escaneado con CamScanner
9:31PM © I E O -
< Errores del Proyecto
Capa: Drenaje_Sencillo
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Drenaje_Sencillo.gpkg|
layername=Drenaje_Sencillo
Capa: Indice
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/lndice.gpkg|Iayername=|ndíce
Capa: Isla
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/lsla.gpkg|Iayername=|s|a
Capa: Jaguey_R
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Jaguey_R…gpkg||ayername=Jaguey_R
Capa: Laguna
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Laguna.gpkg||ayername=Laguna
Capa: Municipios
No se puede cargar la fuente: /storage/emulated/0/
o o - T
Escaneado con CamScanner
231 P MOE O --- - a (24)O
< Errores del Proyecto
Capa: Osmand_18_Sep_2024
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Osmand_18_Sep_2024,gpkg|
layername=0smand_18_Sep_2024
Capa: Otros_Cuerpos_Agua
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_IOtros_Cuerpos_Agua.gpkg|
layername=0tros_Cuerpos_Agua
Capa: Pantano
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Pantano.gpkg|layername=Pantano
Capa: Piscina
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Piscina.gpkg|Iayername=Piscina
Capa: Pista_Aterrizaje_R
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_IP¡sta_Aterrizaje_R.gpkg|
layername=Pista_Aterrizaje_R
o o - T
Escaneado con CamScanner
231PMOME O -- 0O a 24O
< Errores del Proyecto
Capa:
Puntos_Muestro_Campo_Provisionales
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/
Puntos_Muestro_Campo_Provisionales.gpkg|
layername=Puntos_Muestro_Campo_Provisionales
Capa: R_TERRENO_copiar
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/R_TERRENO_copiar.gpkg|
layername=R_TERRENO_copiar
Capa:
Shape_suelos_Preliminar_Estero_OU
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/
Shape_suelos_Preliminar_Estero_OU.gpkg|
layername=Shape_suelos_Preliminar_Estero_OU
Capa: Vereda
No se puede cargar la fuente: /storage/emulated/0/
Android/data/uk.co.lutraconsulting/files/projects/
EsteroAyB_/Vereda.gpkg|layername=Vereda
Capa: Via
o o - T
Escaneado con CamScanner
231PMOME O -- O a- 0XO
< Errores del Proyecto
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Croquis.gpkg.()
2024-09-19T02:31:03.1827 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Curva_Nivel.gpkg.()
2024-09-19T02:31:03.1887 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Departamentos.gpkg.()
2024-09-19T02:31:03.1937 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Drenaje_Doble.gpkg.()
2024-09-19T02:31:03.1997 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Drenaje_Sencillo.gpkg.()
2024-09-19T02:31:03.207Z QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Indice.gpkg.()
2024-09-19T02:31:03.2187 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Isla.gpkg.()
2024-09-19T02:31:03.224Z QGIS OGR: Warning:
T
Escaneado con CamScanner
9:31PM © I E O -
< Errores del Proyecto
Log de QGIS
2024-09-19T02:31:03.1277 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
AI_FB_Preliminar_20240912.gpkg.()
2024-09-19T02:31:03.1337 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Administrativo_P.gpkg.()
2024-09-19T02:31:03.1387 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Bloques_EsteroAB_20240912.gpkg.()
2024-09-19T02:31:03.1497 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Colombia.gpkg.()
2024-09-19T02:31:03.1547 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Construccion_P_20240912.gpkg.()
2024-09-19T02:31:03.171Z QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Construccion_P.gpkg.()
2024-09-19T02:31:03.177Z QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
T
Escaneado con CamScanner
9:31PM © I & O -
< Errores del Proyecto
2024-09-19T02:31:03.2247 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Jaguey_R.gpkg.()
2024-09-19T02:31:03.2297 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Laguna.gpkg.()
2024-09-19T02:31:03.2357 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Municipios.gpkg.()
2024-09-19T02:31:03.240Z QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Osmand_18_Sep_2024.gpkg.()
2024-09-19T02:31:03.247Z QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Otros_Cuerpos_Agua.gpkg.()
2024-09-19T02:31:03.2537 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
Pantano.gpkg.()
2024-09-19T02:31:03.2587 QGIS OGR: Warning:
Cannot open /storage/emulated/0/Android/data/
uk.co.lutraconsulting/files/projects/EsteroAyB_/
T
Escaneado con CamScanner
9:31PM © I E O -
< Errores del Proyecto
2024-09-19T02:31:03.3087 QGIS : Warning: 27
unavailable layer(s) found:
2024-09-19T02:31:03.3087 QGIS : Warning: * ../
EsteroAyB_/AI_FB_PreIimínar_20240912.gpkg|
layername=Al_FB_Preliminar_20240912
2024-09-19T02:31:03.3087 QGIS : Warning: * ../
EsteroAyB_/Administrativo_P.gpkg|
layername=Administrativo_P
2024-09-19T02:31:03.3087 QGIS : Warning: * ../
EsteroAyB_/BIoques_EsteroAB_20240912.gpkg|
layername=Bloques_EsteroAB_20240912
2024-09-19T02:31:03.3087 QGIS : Warning: * ../
EsteroAyB_/Colombia.gpkg|layername=Colombia
2024-09-19T02:31:03.3097 QGIS : Warning: *../
EsteroAyB_/Construccion_P_20240912.gpkg|
layername=Construccion_P_20240912
2024-09-19T02:31:03.3097 QGIS : Warning: * ../
EsteroAyB_/Construccion_P.gpkg|
layername=Construccion_P
2024-09-19T02:31:03.309Z QGIS : Warning: * ../
EsteroAyB_/Croquis.gpkg|Iayername=Croquis
2024-09-19T02:31:03.3097 QGIS : Warning: *../
EsteroAyB_/Curva_Nível.gpkg|
layername=Curva_Nivel
2024-09-19T02:31:03.309Z QGIS : Warning: *../
EsteroAyB_/Departamentos.gpkg|
layername=Departamentos
o o - T
Escaneado con CamScanner
9:32PM O Il & O —
< Errores del Proyecto
layer Jaguey_R
2024-09-19T02:31:03.4097 Project load: Invalid
layer Laguna
2024-09-19T02:31:03.4097 Project load: Invalid
layer Municipios
2024-09-19T02:31:03.4107 Project load: Invalid layer
Osmand_18_Sep_2024
2024-09-19T02:31:03.4107 Project load: Invalid layer
Otros_Cuerpos_Agua
2024-09-19T02:31:03.4107 Project load: Invalid layer
Pantano
2024-09-19T02:31:03.4107 Project load: Invalid layer
Piscina
2024-09-19T02:31:03.4107 Project load: Invalid layer
Pista_Aterrizaje_R
2024-09-19T02:31:03.4107 Project load: Invalid layer
Puntos_Muestreo_Preliminar
2024-09-19T02:31:03.4107 Project load: Invalid layer
Puntos_Muestro_Campo_Provisionales
2024-09-19T02:31:03.4107 Project load: Invalid layer
R_TERRENO_copiar
2024-09-19T02:31:03.4107 Project load: Invalid layer
Shape_suelos_Preliminar_Estero_OU
2024-09-19T02:31:03.4117 Project load: Invalid layer
Vereda
2024-09-19T02:31:03.411Z Project load: Invalid layer
Via
o o - T
Escaneado con CamScanner
232PMOME O --- - a (24)O
< Errores del Proyecto
2024-09-19T02:31:03.3097 QGIS : Warning: *../
EsteroAyB_/Departamentos.gpkg|
layername=Departamentos
2024-09-19T02:31:03.309Z QGIS : Warning: * ../
EsteroAyB_/Drenaje_Doble.gpkg|
layername=Drenaje_Doble
2024-09-19T02:31:03.3097 QGIS : Warning: * ../
EsteroAyBJDrenaje_SenciHo.gpkg|
layername=Drenaje_Sencillo
2024-09-19T02:31:03.3097 QGIS : Warning: * ../
EsteroAyB_/Indice.gpkg|layername=Indice
2024-09-19T02:31:03.3097 QGIS : Warning: *../
EsteroAyB_/Isla.gpkg|layername=Isla
2024-09-19T02:31:03.3097 QGIS : Warning: * ../
EsteroAyB_/Jaguey_R.gpkg|Iayername:Jaguey_R
2024-09-19T02:31:03.3097 QGIS : Warning: * ../
EsteroAyB_/Laguna.gpkg|Iayername=Laguna
2024-09-19T02:31:03.3097 QGIS : Warning: *../
EsteroAyB_/Municipios.gpkg|Iayername:Municipios
2024-09-19T02:31:03.309Z QGIS : Warning: * ../
EsteroAyB_/Osmand_18_Sep_2024.gpkg|
layername=0smand_18_Sep_2024
2024-09-19T02:31:03.3097 QGIS : Warning: *../
EsteroAyB_/Otros_Cuerpos_Agua.gpkg|
layername=0tros_Cuerpos_Agua
2024-09-19T02:31:03.3107 QGIS : Warning: * ../
EsteroAyB_/Pantano.gpkgIIayername=Pantano
o o - T
Escaneado con CamScanner
9:32PM © I E O
< Errores del Proyecto
9161 UAY L YYY USA pUS_Nyua.ypny |
layername=0tros_Cuerpos_Agua
2024-09-19T02:31:03.3107 QGIS : Warning: * ../
EsteroAyB_/Pantano.gpkg|Iayername:Pantano
2024-09-19T02:31:03.3107 QGIS : Warning: * ../
EsteroAyB_/Piscina.gpkg|Iayername=Piscina
2024-09-19T02:31:03.3107 QGIS : Warning: * ../
EsteroAyB_/Pista_Aterrizaje_R.gpkg|
layername=Pista_Aterrizaje_R
2024-09-19T02:31:03.3107 QGIS : Warning: * ../
EsteroAyB_/Puntos_Muestreo_Preliminar.gpkg|
layername=Puntos_Muestreo_Preliminar
2024-09-19T02:31:03.3107 QGIS : Warning: * ../
EsteroAyB_/
Puntos_Muestro_Campo_Provísionales.gpkgI
layername=Puntos_Muestro_Campo_Provisionales
2024-09-19T02:31:03.3107 QGIS : Warning: * ../
EsteroAyB_/R_TERRENO_copiar.gpkg|
layername=R_TERRENO_copiar
2024-09-19T02:31:03.3107 QGIS : Warning: * ../
EsteroAyB_/
Shape_sueIos_PreIíminar_Estero_OU.gpkg|
layername=Shape_suelos_Preliminar_Estero_OU
2024-09-19T02:31:03.3107 QGIS : Warning: * ../
EsteroAyB_/Vereda.gpkg|Iayername=Vereda
2024-09-19T02:31:03.3107 QGIS : Warning: * ../
EsteroAyB_/Via.gpkg[Iayername:Via
2024-09-19T02:31:03.4077 Project load: Invalid layer
o o - T
Escaneado con CamScanner

**Comment by ValentinBuira** [comment]
Hi @camicasilo  thanks for the report.
However, this appear to be an issue on the mobile app, do you think  you could reopen the issue in [MergingMap/mobile](https://github.com/MerginMaps/issues) repository ?

Additional info like, the step to reproduce,  the project you working, the app version, would also help us solve your issue
