### ISSUE TITLE
Replace view fejler i udvidelser

### ISSUE THREAD

**Issue by Ellebjerg** [MerginMaps/qgis-plugin#634]
Når jeg forsøger at tilføje kolonner til udvidelser.punkt_tilsynstrae med replace view, får jeg at vide, at det ikke kan lade sig gøre, og at jeg i stedet skal benytte alter view... Det er uanset, om jeg bruger min egen bruger eller hvidovre_admin.

Jeg kan derimod godt få lov at slette viewet og så oprette det igen med de nye kolonner. Hvad er logikken i det?

Det er ikke hensigtsmæssigt at tilføje dem med alter view, da jeg gerne vil have kolonnerne ud i en rækkefølge, der giver mening.

**Comment by ValentinBuira** [comment]
Hi Ellebjerg, 

I tried to translate your bug report with deepl but I got not luck. It looks like you have an issue with postgresql/PostGis rather than Mergin Maps product.

Closing this but feel free to reopen the issue in english if you can

**Comment by Ellebjerg** [comment]
Sorry! Issue should have been to Septima, who hosts our Mergin Server.
