### ISSUE TITLE
Billeder til MinIO

### ISSUE THREAD

**Issue by Ellebjerg** [MerginMaps/qgis-plugin#635]
Hvordan skal properties for fotos sættes op i QGIS for at gemme til MinIO? Jeg kan ikke helt genneskue, om billederne fortsat skal gemmes som attachment, og de så bliver flyttet af media-sync, eller om layer properties i QGIS skal sættes anderledes op med brugen af MinIO.

![Image](https://github.com/user-attachments/assets/1c2ff355-68ad-48b4-939a-af061e146099)

**Comment by ValentinBuira** [comment]
Hi @Ellebjerg, I translated this bug report as best I could with deepl. Please favor the use on english if you can speak it.

This look like more a support request about setup Media Sync with MinIO than a bug request. you can find the documentation about media sync and MinIO here : https://merginmaps.com/docs/dev/media-sync/

I forwarded your demand to the support, you can also contact them or join the [slack community server ](https://merginmaps.com/community/join)for help

**Comment by Ellebjerg** [comment]
Sorry, my mistake. This issue should have been to Septima, who hosts our Mergin Server and has set up MinIO for us.
